### ISSUE TITLE
About idx2multi

### ISSUE THREAD

**Issue by SmallHedgehog** [lijx10/SO-Net#10]
https://github.com/lijx10/SO-Net/blob/8afd4877cc3bcce6755ee28d7658ca7f80beda72/util/som.py#L80

It should be (i // self.rows, i % self.cols)

**Comment by lijx10** [comment]
I think it is `(i // self.cols, i % self.cols)`. The function `idx2multi` converts an idx into (i, j) coordinate. Take an example that a grid is 3x5, idx 0 is (0, 0), idx 4 is (0, 4), idx 5 is (1, 0). It is row-major.

On the other hand, if it is column major, it is `(i // self.rows, i % self.rows)`.
