### ISSUE TITLE
question about decoder with conv?why the less params

### ISSUE THREAD

**Issue by AmyWan** [lijx10/SO-Net#11]
the branch of conv in decoder.the first conv's prams size is 1024*3*3*1024 ,lager than the decoder with fc,why u use the conv branch ?why did u directly use fc?

**Comment by lijx10** [comment]
The reasons of using deconv are 2-fold:
**1. Less params.** 
1.1 Take an example that the feature vector is size 1024, and we want to reconstruct 1024 points. 
- FC: **Assume that the number of neurons are non-increasing.** The first layer is at least 1024 -> 3*1024 (each point has x,y,z coordinates). That is param amount: 1024*3*1024. In the following layers, the number of params will be 3*1024*3*1024.
- deconv: the first layer, the convolution param amount: 1024*3*3*1024. But in the following layers, the number of params are decreasing.
- This effect is more obvious if we are reconstructing 5000 points. Each layer of FC takes at least 3*5000*3*5000, which is huge. But for deconv, the we have similar number of params as in the case of reconstructing 1024 points.
- That is, deconv is much more scalable.
- Of course, we don't have to **assume that the number of neurons are non-increasing** for FC. In this case, the number of params depends on how to implement FC/deconv. It is meaning less to make absolute comparison.

2. **Deconv has better performance**
- In experiments, reconstructing large number points with FC will result in disappointing performance.
- In real objects / scenes, each point is not totally independent to another point. Hence it is not necessary to use FC. Deconv is more suitable.
