### ISSUE TITLE
Is there any already-trained model available? (3D retrieval)

### ISSUE THREAD

**Issue by SkyeFromKindergarten** [lijx10/SO-Net#13]
Hi, thanks for your great work and patient guidance.

I want to know if there is a already-trained model for 3D retrieval available for a test demo? Because I have few computing source in school lab to train a model from zero. 

No offence to your work~I will be appreciate if you provided one.

**Comment by lijx10** [comment]
The retrieval model is here:
https://drive.google.com/drive/folders/1yj-ka2pU5vMEAe5sZEF0a5VyYK0cCpYo?usp=sharing

The output of the encoder is a feature vector for each input point cloud. This feature vector can be used for retrieval.

**Comment by SkyeFromKindergarten** [comment]
Thanks for your reply!

I can't find test.py code you mentioned in ReadMe, so we should code ourselves, right?

**Comment by lijx10** [comment]
I have uploaded a test.py to SHREC16. This is a file to save the feature vector to disk. The evaluation code is by the SHREC16 official code. `http://shapenet.cs.stanford.edu/shrec16/`

**Comment by SkyeFromKindergarten** [comment]
Sorry to disturb you.

In your code test.py (in shrec16),  you have import SHREC2016Loader from data.shrec2016_loader to load testset, but there's no shrec2016_loader.py in data file. Is the test data loading process the same as the training data loading process (share data.modelnet_shrec_loader code)?

Thanks for your patient, I'm still trying to work it out ~

**Comment by SkyeFromKindergarten** [comment]
I think it's right to load test data via data.modelnet_shrec_loader.py because mode is set to be 'test'. So there's maybe some mistakes in test.py (in shrec16) you uploaded lately.

Please correct me if there is anything wrong.
