### ISSUE TITLE
why your prepared dataset can not be download? 

### ISSUE THREAD

**Issue by dangjisheng** [lijx10/SO-Net#15]

**Comment by lijx-nutonomy** [comment]
It is here:
https://drive.google.com/drive/folders/184MbflF_RbDX9MyML3hid7OxsYJ8oQQ7

**Comment by dangjisheng** [comment]
Think you for your reply，but this website can not open in China，do you know why？




------------------ Original ------------------

**Comment by lijx10** [comment]
Google drive is blocked by the government. Sorry that I can't put it in Chinese drives like BaiduYun because they are extremely slow abroad.

**Comment by dangjisheng** [comment]
Think for your reply，I will consider other 
method


------------------ Original ------------------
