### ISSUE TITLE
Has anyone successfully reproduced the code for the sorting task for this article on modelnet40??

### ISSUE THREAD

**Issue by dangjisheng** [lijx10/SO-Net#16]
Has anyone successfully reproduced the code for the sorting task for this article on modelnet40??

**Comment by lijx10** [comment]
What is the sorting task of ModelNet40? There are classification on ModelNet and shape retrieval on ShapeNet. Do you mean the shape retrieval?

**Comment by dangjisheng** [comment]
> What is the sorting task of ModelNet40? There are classification on ModelNet and shape retrieval on ShapeNet. Do you mean the shape retrieval?

Think you for your reply,I mean that classification task on ModelNet40 dataset,I want to know weather your code about this task is full?

**Comment by lijx10** [comment]
Most of the codes are the same as that I used for the paper.

**Comment by dangjisheng** [comment]
OK，think you.




------------------ Original ------------------
