### ISSUE TITLE
OSError：library nvvm not found

### ISSUE THREAD

**Issue by Timaces** [lijx10/SO-Net#17]
When i  run the program ,I met the question:OSError：library nvvm not found.What I can do?
thank you .

**Comment by lijx-nutonomy** [comment]
Please follow the instructions in Readme to install the numba:

A summary of installing/using numba without conda: 
1. Install llvm-6.0 
2. Build and install llvmlite 
3. sudo pip3 install numba 
4. Set environment variables, example
~~~
export LLVM_CONFIG=/usr/lib/llvm-6.0/bin/llvm-config  
export NUMBAPRO_NVVM=/usr/local/cuda/nvvm/lib64/libnvvm.so
export NUMBAPRO_LIBDEVICE=/usr/local/cuda/nvvm/libdevice
~~~

Numba is required by 3-layer SO-Net and accelerated kNN search. Another method to remove the dependency of Numba is to use cuda extentions. The codes can be found in my other repository: rot-equ-net
