### ISSUE TITLE
ModelNet10 dataset issue

### ISSUE THREAD

**Issue by usherbob** [lijx10/SO-Net#18]
Hi, Jiaxin, Thanks for your work and sharing your code. You use **ModelNet10** dataset in your experiment, may you share the ModelNet10 dataset? It seems that the dataset released by [Princeton](http://modelnet.cs.princeton.edu/) could not be used directly. And I could not find it under [PointNet2](https://github.com/charlesq34/pointnet2) repository.

**Comment by lijx-nutonomy** [comment]
The ModelNet10 is a subset of ModelNet40. You may use the ModelNet40 provided in this repository, i.e.,https://drive.google.com/open?id=184MbflF_RbDX9MyML3hid7OxsYJ8oQQ7

Switch between ModelNet40 and ModelNet10 can be done easily by modifying the the Option datastructure in the code. The dataloader supports both ModelNet40 and ModelNet10.

**Comment by usherbob** [comment]
Thanks, I will have a try.
