### ISSUE TITLE
**Segmentation Fault** in autoencoder

### ISSUE THREAD

**Issue by everange-ustc** [lijx10/SO-Net#19]
Hi, thanks for sharing the source code. I have encounted some problems while implementing auto-encoder script.
The environmetal setting is as follows:
---Pytorch 0.4.1
---faiss is installed by anaconda

When I use the model40 dataset, there exist several problems, like 
AttributeError: 'Namespace' object has no attribute 'rot_horizontal'
After setting this to False, then the script  can run and meets new problem:

------------ Options -------------
activation: relu
batch_size: 8
bn_momentum: 0.1
bn_momentum_decay: 0.6
bn_momentum_decay_step: None
checkpoints_dir: ./checkpoints
classes: 40
dataroot: ../data/modelnet40-normal_numpy/
dataset: modelnet
device: cuda:0
display_id: 200
display_winsize: 256
dropout: 0.5
feature_num: 1024
gpu_id: 0
input_pc_num: 1024
k: 3
lr: 0.001
nThreads: 8
name: train
node_num: 64
normalization: batch
output_conv_pc_num: 1024
output_fc_pc_num: 256
output_pc_num: 1280
random_pc_dropout_lower_limit: 1
rot_horizontal: True
rot_perturbation: True
som_k: 9
som_k_type: avg
surface_normal: True
translation_perturbation: True
-------------- End ----------------
#training point clouds = 9843
**Segmentation Fault**

Is there anything I forget to modify, I hope you can help me to solve this problem, thanks.

**Comment by lijx-nutonomy** [comment]
I didn't encounter this issue before. Did you solve that? What's the cause?
