### ISSUE TITLE
shrec16/test.py  error

### ISSUE THREAD

**Issue by wusuoweima** [lijx10/SO-Net#20]
line 6 of shrec16/test.py  
![image](https://user-images.githubusercontent.com/30040019/61346035-ef487580-a889-11e9-9e0c-ee6ca0c4f180.png)

line 24 of shrec16/test.py  
![image](https://user-images.githubusercontent.com/30040019/61346093-1bfc8d00-a88a-11e9-9a82-36e9dcdeab79.png)

Could you please upload related code? Thank you very much.

**Comment by wusuoweima** [comment]
@lijx10

**Comment by Wuziyi616** [comment]
I think you can refer to issue13: https://github.com/lijx10/SO-Net/issues/13

**Comment by wusuoweima** [comment]
> I think you can refer to issue13: #13

but issue13 is also has the same error : no shrec2016_loader.py

**Comment by Wuziyi616** [comment]
> 
> 
> > I think you can refer to issue13: #13
> 
> but issue13 is also has the same error : no shrec2016_loader.py

Yeah and in issue 13 he finally said that he could use data.modelnet_shrec_loader to load the test data. I think you can refer to that issue in detail.

**Comment by lijx10** [comment]
@wusuoweima Yes, @Wuziyi616 is correct. With minor midifcation to the Options, data.modelnet_shrec_loader will be able to load shrec16.
