### ISSUE TITLE
How to test the model on SHREC2016 retrieval challenge?

### ISSUE THREAD

**Issue by Wuziyi616** [lijx10/SO-Net#21]
Hello, what a great work you have done. But I still have some questions about testing the model and get the result on SHREC2016 retrieval task. I have run test.py and get those .txt files, also I have downloaded the evaluation files from the website, then what should I do next? Can I directly run the node js file as described in its ReadMe file as "./evaluate.js path/to/dir/with/results/methodName/"? And the path is the directory where I save the folders for all the models and it's retrieval results right?
Looking forward to your reply!

**Comment by wusuoweima** [comment]
I also encountered this problem, and I have send an email to you.

**Comment by wusuoweima** [comment]
@lijx10 @lijx-nutonomy

**Comment by lijx10** [comment]
The formats of SHREC16 results are described in http://shapenet.cs.stanford.edu/shrec16/format.html

Is there any problem running the evaluate.js?

**Comment by Wuziyi616** [comment]
It works. Thanks a lot!
