### ISSUE TITLE
Question about point cloud transformation

### ISSUE THREAD

**Issue by sunnyHelen** [lijx10/SO-Net#26]
Hi, I'm very new to deal with point cloud. So maybe my question is not quite related to your repository. 
I want to ask if I have a point cloud(Nx3), a rotation matrix(3x3) and translation matrix(1x3). How could I get the point cloud after the transformation(rotation and translation→4X4)? 
For rotation, I guess just multiply with the matrix? And how about translation?
Your help will be highly appreciated.

**Comment by lijx10** [comment]
You may use homogeneous coordinate transformation. In the matlab syntax, a point can be represented as p = [x, y, z, 1]. The rotation R (3x3 matrix) and translation t (3x1 matrix) can be represented by a transformation matrix G = [R, t; 0, 1], where the '0' is a 1x3 zero matrix. Then the point p can be transformed by G * p.

**Comment by sunnyHelen** [comment]
Thanks a lot with your apply. I'll try it.
