### ISSUE TITLE
index_max builds but fails at runtime

### ISSUE THREAD

**Issue by joeydash** [lijx10/SO-Net#27]
I'm running the classification task but I get the following error:

system info: 
python 3.7
pytorch 1.2
cuda 10.2
faiss toolkit for cuda 10

------------ Options -------------
activation: relu
batch_size: 8
bn_momentum: 0.1
bn_momentum_decay: 0.6
bn_momentum_decay_step: None
checkpoints_dir: ./checkpoints
classes: 40
dataroot: /home/raman/Reconstruction/modelnet40-normal_numpy/
dataset: modelnet
device: cpu
display_id: 200
display_winsize: 256
dropout: 0.7
feature_num: 1024
gpu_id: 0
input_pc_num: 5000
k: 3
lr: 0.001
nThreads: 8
name: train
node_num: 64
normalization: batch
pretrain: None
pretrain_lr_ratio: 1
random_pc_dropout_lower_limit: 1
rot_horizontal: False
rot_perturbation: False
som_k: 9
som_k_type: avg
surface_normal: True
translation_perturbation: False
-------------- End ----------------
Traceback (most recent call last):
  File "train.py", line 20, in <module>
    from models.classifier import Model
  File "../models/classifier.py", line 11, in <module>
    from . import networks
  File "../models/networks.py", line 17, in <module>
    import index_max
ImportError: /home/raman/anaconda3/lib/python3.7/site-packages/index_max-0.0.0-py3.7-linux-x86_64.egg/index_max.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN2at19UndefinedTensorImpl10_singleton

**Comment by zeal-github** [comment]
@joeydash Have you solved the problem? Since I encountered the same problem as you!
