### ISSUE TITLE
Supplementary material

### ISSUE THREAD

**Issue by yaping222** [lijx10/SO-Net#29]
Hi Jiaxin, 
Thank you very much for your great work! I'm quite interested in how to initialize the SOM. The CVPR2018 paper mentioned it's in the supplementary material. Could you tell me where I can find the supplementary material?

**Comment by lijx10** [comment]
It is in the arxiv: https://arxiv.org/abs/1803.04249

**Comment by yaping222** [comment]
Thank you so much!
