### ISSUE TITLE
how to run?

### ISSUE THREAD

**Issue by gaohongfein** [lijx10/SO-Net#3]

**Comment by gaohongfein** [comment]
I want to run your code. for example for classification, the code need also the faiss and other optional dependancy. how to change it？

**Comment by lijx10** [comment]
### Faiss
Faiss is used mainly in two places,
- Computing the k-nearest neighbor in dataloader e.g. `data/modelnet_shrec_loader.py`. The returned `som_knn_I` is later used in the `KNNModule` in `models/network.py`. You may set `precomputed_knn_I=None` when calling the forward function of `KNNModule`. Hence, the Faiss dependence can be removed for classification and segmentation.
- Computing the Chamfer distance in Autoencoder. The nearest neighbor search can be easily replaced with brute-force searching. However, brute-force search is much slower than using Faiss.

### numba
It is a lot more complicated to remove the dependence on numba. There are customized cuda functions in `models/operations.py`, including functions to create the SOM feature map. An option is to rewrite those functions with C language with cuda support, and import it to python.
