### ISSUE TITLE
Data augmentation not work?

### ISSUE THREAD

**Issue by usherbob** [lijx10/SO-Net#31]
Hello all,

It seems that data augmentation for translation and rotation did not work in SO-Net, even worse, enabling `rot_horizontal`, `rot_pertubation`, `translation_pertubation` in [options.py](https://github.com/lijx10/SO-Net/blob/master/modelnet/options.py#L49) hurt the final classification performance.

We all know that many models use data augmentation to increase robustness to point cloud rotation and translation. I have not tried the performance of SO-Net under the rotating point cloud yet. But I believe the absence of rotation augmentation hurts. 

Any discussions could be helpful.

**Comment by lijx-nutonomy** [comment]
Yes rotation augmentation is not enable for ModelNet40, ShapeNet etc. Rotation is a known problem for point cloud networks. The performance of SO-Net or any other method will be very bad if tested with rotated objects but trained without rotation augmentation. Therefore, one has to train the model with rotation augmentation if rotated objects will be forwarded into the network. Training with rotation augmentation will lead to slight performance drop.
