### ISSUE TITLE
The function of index_max.

### ISSUE THREAD

**Issue by zeal-github** [lijx10/SO-Net#32]
Thanks for your work!
I have a few questions about the index_max function. I am not familiar with cuda. The index_max seems is used to max pooling for all point features where the points allocated in one SOM cluster.
Do I understand right? Why do you implement it with cuda? Does it speed up a lot?
Appreciated if you can reply.

**Comment by lijx10** [comment]
For the speed. An alternative implementation is to run for loop in pytorch, to get a max-pooling for each node. In the case that node number is small, e.g., <10, this practice should be fine. However, in most cases, the node number is like 64, 128, which means python for loop will be quite slow.

**Comment by zeal-github** [comment]
@lijx10 Can I implement like this：
```
first_pn_out_repeat = first_pn_out.unsqueeze(-1).repeat(1, 1, 1, M) # B x C x kN x M
first_pn_out_repeat = torch.mul(first_pn_out_repeat, mask.float())
first_pn_out_masked_max, _ = torch.max(first_pn_out_repeat, dim=2, keepdim=False) # B x C x M
```
I think the function is the same except all the features are smaller than 0.

**Comment by lijx10** [comment]
Killing features smaller than 0 is fine becuase it equals to adding a relu. So theoretically it should be fine to use your implementation, but note that in this case you have to train your own model, instead of loading pre-trained ones.

The problem is that such pytorch implementation can be very slow because it is repeating the tensor by M times.

**Comment by zeal-github** [comment]
Thanks for your reply and your work again! I do train my own model. But I think that even replace your index_max function with mine it's also capable to load your pre-trained model (maybe need some trick) since this operation is parameter-free.
And yes , it may be slow.
