### ISSUE TITLE
how to train som with my own data?

### ISSUE THREAD

**Issue by dongtuu** [lijx10/SO-Net#6]
I have seen some codes in /data/build_som/util/, it seems som.py is the file for training som. But I'm not sure about how to use it. Can you offer some instructions like training som with modelnet?

**Comment by lijx10** [comment]
An full example of using som.py to process SHREC16 dataset is provided in `data/build_som/save_som.ipynb`.

Basically, a typical usage is like this:
- Create an instance of the SOM() class:
`som_builder = som.SOM(rows, cols, 3, gpu_ids)`

- Prepare the point cloud as a 3xN pytorch tensor

- Train the SOM.
```
som_builder.optimize(pc)  # pc: 3xN float tensor
node = som_builder.node  # 3xM float tensor
```

som.py supports both CPU training and GPU training, which can be controlled with the parameter `gpu_ids`.

**Comment by dongtuu** [comment]
Oh I find it. I didn't think it's an instruction before as the suffix is uncommon for me. Thank you very much.

**Comment by GCH-upup** [comment]
Your providing datasets are so dissatisfa and disgust !!!
